"""add_images

Revision ID: b9ef7b4f85dd
Revises: fdb369e2a226
Create Date: 2026-05-21 23:29:23.008442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from application.core.config import settings

# revision identifiers, used by Alembic.
revision: str = 'b9ef7b4f85dd'
down_revision: Union[str, Sequence[str], None] = 'fdb369e2a226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('image_path', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True), schema='application')
    op.drop_column('blog_post', 'image', schema='application')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='application')
    op.drop_column('blog_post', 'image_path', schema='application')
    # ### end Alembic commands ###
